

###
## nuevo incorrecto
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type:application/json

{
    "nickname": "prueba",
    "email": "@",
    "password":"a",
    "roles":["admin"]
}
###
##nuevo ok

POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type:application/json

{
    "nickname": "joserra",
    "nombre": "Professor Jose Ramon",
    "email": "joseramos@gmail.com",
    "password":"NoTeLoDigo@1",
    "roles":["admin"]
}
###
## login ok
POST http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "joserra",
    "password": "NoTeLoDigo@1"
}
###
## get allPorteros


## nuevo prueba
POST  http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "prueba",
    "nombre":"prueba ismael",
    "email":"ismael@gmail.com",
    "password":"NoTeLoDigo@1"
}

###
##login OK

POST  http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "prueba",
    "password":"NoTeLoDigo@1"
    
}

###
###
##getAllPorteros con JWGT

GET  http://localhost:8090/api/v1/questions HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI

###
## getQuestionRandom with a category
GET http://localhost:8090/api/v1/questions/category/animals/table/1  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI

###
## Send answer Question
GET  http://localhost:8090/api/v1/questions/answer?resultsCorrectAnswer=Albanyz&idPregunta=7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI
### getStartTablero
POST http://localhost:8090/api/v1/createBoard/prueba  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI

###

### addPlayer
POST http://localhost:8090/api/v1/addPlayer/name/joserra/table/1  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI

### getTableroStatus


GET  http://localhost:8090/api/v1/getStatusBoard/1  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI

### getStartGame

POST http://localhost:8090/api/v1/startGame/1  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI
###

### getNumRandom1_4
GET  http://localhost:8090/api/v1/rolldice/prueba/table/1  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI


### doMovement

POST  http://localhost:8090/api/v1/movePlayer/joserra/number/2/table/1  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI

### checkMovement

POST http://localhost:8090/api/v1/checkMovement/BONIFICACION/player/joserra/table/1  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDgwMTY0MzEsImV4cCI6MTcwODA1MjQzMX0.uHJELcBalbR1KnOaaTQpCLcB3iSTp1KdlvUlmuSrsyI

###