

###
## nuevo incorrecto
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type:application/json

{
    "nickname": "prueba",
    "email": "@",
    "password":"a",
    "roles":["admin"]
}
###
##nuevo ok

POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type:application/json

{
    "nickname": "joserra",
    "nombre": "Professor Jose Ramon",
    "email": "joseramos@gmail.com",
    "password":"NoTeLoDigo@1",
    "roles":["admin"]
}
###
## login ok
POST http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "joserra",
    "password": "NoTeLoDigo@1"
}
###
## get allPorteros


## nuevo prueba
POST  http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "prueba",
    "nombre":"prueba ismael",
    "email":"ismael@gmail.com",
    "password":"NoTeLoDigo@1"
}

###
##login OK

POST  http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "prueba",
    "password":"NoTeLoDigo@1"
    
}

###
###
##getAllPorteros con JWGT

GET  http://localhost:8090/api/v1/questions HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDc0Njc0NDIsImV4cCI6MTcwNzUwMzQ0Mn0.YS8mhMSwQtNWrUK0-JRmUfHBX5-k7PWcb3ytVytWkps

###
GET http://localhost:8090/api/v1/questions/category/animals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmEiLCJpYXQiOjE3MDc0Njc0NDIsImV4cCI6MTcwNzUwMzQ0Mn0.YS8mhMSwQtNWrUK0-JRmUfHBX5-k7PWcb3ytVytWkps